import { useState, useEffect, useRef } from 'react'
import Editor from 'react-simple-code-editor'
import { highlight, languages } from 'prismjs'
import 'prismjs/components/prism-python'
import 'prismjs/themes/prism-tomorrow.css'
import { usePyScript } from '../hooks/usePyScript'
import type { CoordinateFrame, Vector, FunctionPlot } from '../types'

interface CodePanelProps {
  selectedFrame: CoordinateFrame | null
  onCodeChange: (frameId: string, code: string) => void
  onCodeRun?: (frameId: string, code: string) => void
  onVectorsUpdate?: (frameId: string, vectors: Vector[]) => void
  onFunctionsUpdate?: (frameId: string, functions: FunctionPlot[]) => void
  onVectorsClear?: (frameId: string) => void
  onFunctionsClear?: (frameId: string) => void
  autoExecuteCode?: string | null // When set, automatically execute this code
}

// Default code is now generated by codeGenerator.ts
// This fallback is only used if frame.code is empty
const DEFAULT_CODE = `import numpy as np
from scipy import linalg

# Predefined functions available:
# - draw(vector, color?) - Draw a vector from origin
# - plot(formula, x_min, x_max, color?, num_points?) - Plot a function
`

export default function CodePanel({
  selectedFrame,
  onCodeChange,
  onCodeRun,
  onVectorsUpdate,
  onFunctionsUpdate,
  onVectorsClear,
  onFunctionsClear,
  autoExecuteCode,
}: CodePanelProps) {
  const [localCode, setLocalCode] = useState<string>('')
  const [isRunning, setIsRunning] = useState(false)
  const [executionResult, setExecutionResult] = useState<{ success: boolean; error?: string } | null>(null)
  const { isReady, executeCode, isExecuting } = usePyScript()
  const editorRef = useRef<HTMLDivElement>(null)
  const textareaRef = useRef<HTMLTextAreaElement | null>(null)
  const preRef = useRef<HTMLPreElement | null>(null)
  const lineNumbersRef = useRef<HTMLDivElement | null>(null)

  // Update local code when selected frame changes
  useEffect(() => {
    if (selectedFrame) {
      // Use frame's code if available, otherwise use default
      setLocalCode(selectedFrame.code || DEFAULT_CODE)
      setExecutionResult(null)
    } else {
      setLocalCode('')
      setExecutionResult(null)
    }
  }, [selectedFrame])

  // Auto-execute code when autoExecuteCode is set
  useEffect(() => {
    if (autoExecuteCode && selectedFrame && isReady && !isExecuting) {
      // Update local code first
      setLocalCode(autoExecuteCode)
      // Then execute it
      handleRunWithCode(autoExecuteCode)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoExecuteCode])

  // Sync scroll between textarea, pre element, and line numbers
  useEffect(() => {
    const editorContainer = editorRef.current
    if (!editorContainer) return

    const textarea = editorContainer.querySelector('textarea') as HTMLTextAreaElement
    const pre = editorContainer.querySelector('pre') as HTMLPreElement
    const lineNumbers = lineNumbersRef.current
    
    if (!textarea || !pre) return

    textareaRef.current = textarea
    preRef.current = pre

    const handleScroll = () => {
      if (pre && textarea) {
        pre.scrollTop = textarea.scrollTop
        pre.scrollLeft = textarea.scrollLeft
      }
      if (lineNumbers && textarea) {
        lineNumbers.scrollTop = textarea.scrollTop
      }
    }

    textarea.addEventListener('scroll', handleScroll)
    return () => {
      textarea.removeEventListener('scroll', handleScroll)
    }
  }, [localCode])

  // Sync local code changes back to frame
  const handleCodeChange = (newCode: string) => {
    setLocalCode(newCode)
    if (selectedFrame) {
      onCodeChange(selectedFrame.id, newCode)
    }
  }

  // Handle Tab key to insert spaces (Python standard: 4 spaces)
  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Tab') {
      e.preventDefault()
      const target = e.currentTarget as HTMLTextAreaElement
      const start = target.selectionStart
      const end = target.selectionEnd
      const value = localCode
      
      // If there's a selection, indent/unindent the selected lines
      if (start !== end) {
        const lines = value.split('\n')
        const startLine = value.substring(0, start).split('\n').length - 1
        const endLine = value.substring(0, end).split('\n').length - 1
        
        if (e.shiftKey) {
          // Shift+Tab: Unindent (remove 4 spaces or 1 tab)
          for (let i = startLine; i <= endLine; i++) {
            if (lines[i].startsWith('    ')) {
              lines[i] = lines[i].substring(4)
            } else if (lines[i].startsWith('\t')) {
              lines[i] = lines[i].substring(1)
            }
          }
        } else {
          // Tab: Indent (add 4 spaces)
          for (let i = startLine; i <= endLine; i++) {
            lines[i] = '    ' + lines[i]
          }
        }
        
        const newValue = lines.join('\n')
        const newStart = start + (e.shiftKey ? -4 : 4)
        const newEnd = end + (endLine - startLine + 1) * (e.shiftKey ? -4 : 4)
        
        handleCodeChange(newValue)
        
        // Restore selection after state update
        setTimeout(() => {
          target.setSelectionRange(newStart, newEnd)
        }, 0)
      } else {
        // No selection: insert 4 spaces at cursor
        const newValue = value.substring(0, start) + '    ' + value.substring(end)
        handleCodeChange(newValue)
        
        // Move cursor after inserted spaces
        setTimeout(() => {
          target.setSelectionRange(start + 4, start + 4)
        }, 0)
      }
    }
  }

  const handleRunWithCode = async (codeToExecute: string) => {
    if (!selectedFrame || !isReady) {
      return
    }

    setIsRunning(true)
    setExecutionResult(null)

    // Clear existing vectors and functions before running new code
    if (onVectorsClear) {
      onVectorsClear(selectedFrame.id)
    }
    if (onFunctionsClear) {
      onFunctionsClear(selectedFrame.id)
    }

    // Collect vectors and functions created during execution
    const newVectors: Vector[] = []
    const newFunctions: FunctionPlot[] = []

    // Generate unique IDs for vectors and functions
    const generateId = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`

    try {
      const result = await executeCode(
        codeToExecute,
        selectedFrame.id,
        // onVectorCreated callback
        (vector) => {
          newVectors.push({
            ...vector,
            id: generateId('vec'),
          })
        },
        // onFunctionCreated callback
        (func) => {
          newFunctions.push({
            ...func,
            id: generateId('func'),
          })
        }
      )
      
      if (result.success) {
        setExecutionResult({ success: true })
        
        // Update frame with new vectors and functions
        if (onVectorsUpdate && newVectors.length > 0) {
          onVectorsUpdate(selectedFrame.id, newVectors)
        }
        if (onFunctionsUpdate && newFunctions.length > 0) {
          onFunctionsUpdate(selectedFrame.id, newFunctions)
        }
        
        if (onCodeRun) {
          onCodeRun(selectedFrame.id, codeToExecute)
        }
      } else {
        setExecutionResult({
          success: false,
          error: result.error?.message || 'Unknown error occurred',
        })
      }
    } catch (error: any) {
      setExecutionResult({
        success: false,
        error: error.message || 'Execution failed',
      })
    } finally {
      setIsRunning(false)
    }
  }

  const handleRun = async () => {
    await handleRunWithCode(localCode)
  }

  if (!selectedFrame) {
    return null
  }

  return (
    <div className="h-full p-4 flex flex-col min-h-0 overflow-hidden">
      {!isReady && (
        <div className="mb-4 p-2 bg-warning/20 border border-warning/50 rounded text-sm text-warning">
          Pyodide is loading... (this may take a few seconds)
        </div>
      )}

      {executionResult && (
        <div className={`mb-4 p-2 rounded text-sm ${
          executionResult.success
            ? 'bg-success/20 border border-success/50 text-success'
            : 'bg-error/20 border border-error/50 text-error'
        }`}>
          {executionResult.success ? (
            <span>✓ Code executed successfully</span>
          ) : (
            <div>
              <div className="font-medium">Execution Error:</div>
              <div className="text-xs mt-1">{executionResult.error}</div>
            </div>
          )}
        </div>
      )}

      <div className="flex-1 flex flex-col min-h-0 overflow-hidden">
        <label className="block text-sm font-medium text-text-secondary mb-2 flex-shrink-0">
          Python Code
        </label>
        <div 
          ref={editorRef}
          className="flex-1 relative border border-border rounded bg-bg-primary overflow-hidden flex" 
          style={{ minHeight: 0 }}
        >
          {/* Line numbers */}
          <div 
            ref={lineNumbersRef}
            className="code-editor-line-numbers flex-shrink-0"
          >
            {localCode.split('\n').map((_, index) => (
              <div key={index} className="code-editor-line-number">
                {index + 1}
              </div>
            ))}
          </div>
          <div className="flex-1 relative overflow-hidden">
            <Editor
              value={localCode}
              onValueChange={handleCodeChange}
              onKeyDown={handleKeyDown}
              highlight={(code) => highlight(code, languages.python, 'python')}
              padding={0}
              style={{
                fontFamily: '"Fira Code", "Fira Mono", "Consolas", "Monaco", "Courier New", monospace',
                fontSize: 14,
                lineHeight: 1.5,
                outline: 'none',
                width: '100%',
                height: '100%',
                backgroundColor: '#0f172a',
                overflow: 'auto',
              }}
              textareaClassName="code-editor-textarea"
              preClassName="code-editor-pre"
              placeholder={DEFAULT_CODE}
              tabSize={4}
              insertSpaces={true}
            />
          </div>
        </div>
      </div>

      <div className="mt-4 flex gap-2">
        <button
          onClick={handleRun}
          disabled={!isReady || isRunning || isExecuting}
          className={`flex-1 px-4 py-2 rounded-lg transition-colors text-sm font-medium ${
            !isReady || isRunning || isExecuting
              ? 'bg-bg-secondary text-text-secondary cursor-not-allowed'
              : 'bg-primary text-white hover:bg-blue-600'
          }`}
        >
          {isRunning || isExecuting ? 'Running...' : 'Run'}
        </button>
      </div>
    </div>
  )
}

